apiVersion: extensions/v1beta1
kind: Deployment # 1
metadata:
  name: sa-frontend
spec:
  template:
    metadata:
      labels:
        app: sa-frontend # 6
    spec:
      containers:
        - image: rpoliset/frontend
          imagePullPolicy: Always # 7
          name: sa-frontend
          ports:
            - containerPort: 80
