apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sa-web-app
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      containers:
        - image: rpoliset/dropwizard
          imagePullPolicy: Always
          name: sa-web-app
          ports:
            - containerPort: 8080
